name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone the Repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Install Cross Compilation Dependencies
      run: sudo ./scripts/cross-setup.sh
    
    - name: Cross Build
      run: ./scripts/make.sh
    
    - name: Archive Build Results
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: build
