name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone the Repository
      uses: actions/checkout@v3
    
    - name: Cross Build using Docker
      run: ./scripts/docker-run.sh scripts/make.sh --ci
    
    - name: Archive Build Results
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: build
